### ISSUE TITLE
[ISSUE] cuda11.6下部署该项目发生循环扫描torch版本，无法安装成功

### ISSUE THREAD

**Issue by zydmtaichi** [lenML/Speech-AI-Forge#150]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中
- [X] 我已经确认问题与 API 无关
- [X] 我已经确认问题与 WebUI 无关
- [X] 我已经确认问题与 Finetune 无关

### 你的issues

ubuntu22.04
python3.10
已成功安装如下torch相关包：
torch              1.13.1+cu116
torchaudio         0.13.1+cu116
torchvision        0.14.1+cu116

在安装requirement.txt发生循环扫描torch版本情况，强制指定torch版本会导致循环扫描lightning和vector_quantize_pytorch版本，请解决该安装问题

**Comment by zhzLuke96** [comment]
没有环境不好排查具体问题

pytorch建议使用2.0以上，其余依赖可以参考 `requirements.dev.txt` （ci用的）版本来配置虚拟环境
