### ISSUE TITLE
Support FireRedTTS

### ISSUE THREAD

**Issue by zhzLuke96** [lenML/Speech-AI-Forge#165]
https://github.com/FireRedTeam/FireRedTTS

- [x] pin [FireRedTTS](https://github.com/FireRedTeam/FireRedTTS)
- [x] FRTInfer
- [x] tests

**Comment by zhzLuke96** [comment]
done https://github.com/lenML/Speech-AI-Forge/commit/9d6846780f1b743f5303301ed5fe6a19f6d43255

简评一哈：
这个模型 few shot 效果非常好可以克隆的音色范围非常广，但是就是生成质量略差
特殊token很多，挺有意思的（虽然很多都用不了，可能是它内部tn的问题...）

**Comment by zhzLuke96** [comment]
update:
目前的版本没法用特殊 token 控制情绪和副语音，只能纯文本，据说很快会有发新模型

**Comment by wangfeng35** [comment]
FireRedTTS的tn用的WeTextProcessing，如果windows上没有conda安装的话会报错，启动不了webui。

能否采用chattts的方法进行处理，没装WeTextProcessing就换另一种tn？
