### ISSUE TITLE
[ISSUE] 通过--device_id指定GPU设备对除ChatTTS外模型无效

### ISSUE THREAD

**Issue by Seayar** [lenML/Speech-AI-Forge#169]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中
- [X] 我已经确认问题与 API 无关
- [X] 我已经确认问题与 WebUI 无关
- [X] 我已经确认问题与 Finetune 无关

### 你的issues

服务器中安装有3张显卡，通过--device_id 2指定由第3张显卡运行。在勾选启用人声增强或使用CosyVoice、FireRedTTS等模型时，本进程依然会出现在第1张显卡上。由于其他2张显卡显存耗尽，因此生成音频文件时会报OOM错误。
GPU进程通过nvidia-smi查看得到。

**Comment by zhzLuke96** [comment]
fixed https://github.com/lenML/Speech-AI-Forge/commit/bcf2e561cb6d324d58acecb908d80c8c97695f57

cosyvoice 确实有问题已修复，firered tts没发现具体问题在哪
要是还有问题可以继续反馈，最好附带完整的报错日志

**Comment by Seayar** [comment]
您好，邮件已经收到，我会尽快查看，谢谢！Your Email has been received, I will check as soon as possible,Thank you!

**Comment by Seayar** [comment]
您好，邮件已经收到，我会尽快查看，谢谢！Your Email has been received, I will check as soon as possible,Thank you!
