### ISSUE TITLE
[ISSUE] api接口下流式输出处理

### ISSUE THREAD

**Issue by xhjcxxl** [lenML/Speech-AI-Forge#170]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中
- [X] 我已经确认问题与 API 无关
- [X] 我已经确认问题与 WebUI 无关
- [X] 我已经确认问题与 Finetune 无关

### 你的issues

启动launch.py可以启动服务，并构建api接口可以访问，给出的简单示例运行也没有问题：
```
curl http://localhost:7870/v1/audio/speech \
  -H "Authorization: Bearer anything_your_wanna" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "chattts",
    "input": "我买的这款小米电视 ES55 投屏的时候声音老是断断续续的呢，之前没出现过这种情况",
    "voice": "female2",
    "style": "chat"
  }' \
  --output speech3.mp3
```
**想了解下，如果使用流式输出，需要调用哪个接口，并且客户端怎么请求和接收处理返回的结果呢？有参考实例吗**
流式尝试使用：
```
URL = "http://localhost:7870/v1/xtts_v2/tts_stream?text=我的小学同学李华&speaker_wav=86facdf85d5447daacb30335fa817840&language=zh"
```
但是客户端怎么接收二进制数据处理呢？刚接触chatTTS，不太了解

**Comment by zhzLuke96** [comment]
开不开起流式对于客户端来说都是一样的接受编码之后的音频数据流
客户端你完全可以和非流式请求一样，等到请求结束之后再处理音频数据，或者流式的解码播放音频数据

不清楚你的场景是什么，简单的你可以使用浏览器来测试流式和非流式的效果（用稍微长点的文本），把请求的url贴到浏览器中即可，对于流式生成的请求，还没生成结束浏览器就可以播放

**Comment by xhjcxxl** [comment]
> 开不开起流式对于客户端来说都是一样的接受编码之后的音频数据流 客户端你完全可以和非流式请求一样，等到请求结束之后再处理音频数据，或者流式的解码播放音频数据
> 
> 不清楚你的场景是什么，简单的你可以使用浏览器来测试流式和非流式的效果（用稍微长点的文本），把请求的url贴到浏览器中即可，对于流式生成的请求，还没生成结束浏览器就可以播放

我的场景是，大家chatTTS的api接口服务，然后可以流式接收数据，然后进行处理成音频片段，我看feature里面支持token级别的流式，主要是我不清楚调用哪个api，部署后有很多api接口，哪个接口支持流式，还是说只有带有stream的支持流式；另外接收到的数据是二进制数据，b'xx'，需要怎么操作转换成mp3,wav格式之类的呢？有可以参考的吗

**Comment by xhjcxxl** [comment]
我用下面方法接收流式数据，然后实时播放，但是出现的是杂音，应该是默认参数不对，因为我完整接收后可以正常播放
有什么解决办法吗
`
url = "http://localhost:8001/v1/tts"
p = pyaudio.PyAudio()
        stream = p.open(format=pyaudio.paInt16,
                        channels=1,
                        rate=1024,
                        output=True)
        json_data = {
            "text": "当韩立的这个想法，一直没敢和其他人说起过。否则，一定会使村里人感到愕然，一个乳臭未干的小屁孩，竟然会有这么一个大人也不敢轻易想的念头。要知道，其他同韩立差不多大的小孩，都还只会满村的追鸡摸狗，更别说会有离开故土，这么一个古怪的念头。",
            "language": "zh",
            "spk": "female2",
            "stream": True
        }
        response = requests.get(url, params=json_data)
        for chunk in tqdm(response.iter_content(chunk_size=1024)):
            # audio = (chunk * 32767).astype(np.int16)
            stream.write(chunk)
        stream.stop_stream()
        stream.close()
        p.terminate()`

**Comment by xhjcxxl** [comment]
已解决，格式问题，修改为format=wav格式
