### ISSUE TITLE
[ISSUE] API调用流式输出等待后台编译完才传输

### ISSUE THREAD

**Issue by xhjcxxl** [lenML/Speech-AI-Forge#173]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中
- [X] 我已经确认问题与 API 无关
- [X] 我已经确认问题与 WebUI 无关
- [X] 我已经确认问题与 Finetune 无关

### 你的issues

我在测试api接口的流式输出时，发现一个问题，我使用：`v1/tts，v1/xtts_v2/tts_stream`两种方法进行流式获取请求结果，返回结果播放输出正常，但是请求的时候，后台需要编译完才进行流式数据传输，是不是哪里设置参数不对呢？
![image](https://github.com/user-attachments/assets/1e73f740-e040-48c3-9788-5ec55d77476e)
每次都是code编译走完了，然后我的http才开始接收请求，麻烦请教下是不是哪里参数设置错了呢

**Comment by xhjcxxl** [comment]
参考其他解决办法，增加compile指令后，api后台卡死，关闭tqdm进度条后，还是没有反应，不知道什么时候能有结果

![image](https://github.com/user-attachments/assets/5ca5a4fd-adba-40eb-bbb5-94ccf571c00a)

**Comment by zhzLuke96** [comment]
没有什么其他特别的参数，对于 `tts` 接口设置 `stream=True` 即可，对于 `xtts_v2/tts_stream` 接口不需要指定 stream

没有代码没有复现你的情况，我大概估计你的情况可能是短文本合成

首先流式生成受限生成质量问题，会有一个 token window， 在足够的 token 生成了之后才会开始编码并推流，所以对于短文本合成，流式和非流式时间差距可能不大
其次如果你的请求设置了编码格式，在推流前还有编码过程这个过程也可能带来一定的延迟

具体想体验流式的效果可以启动 `python launch.py` 之后在 `http://localhost:7870/playground/#stream` 中用长文本调试

---
关于 `--compile` 这里可能有点歧义，启动参数的 compile 是开启模型编译，而它和 code 之后的 compile 并不是一个意思，所以，你也不需要开启 compile。并且目前个人使用不建议开启模型编译，开启 compile 之后需要先编译模型，编译完成之后才能推理

**Comment by xhjcxxl** [comment]
> 在足够的 token 生成了之后才会开始编码并推流

在足够的 token 生成了之后才会开始编码并推流，这个有设置条件吗，我这边想控制首包的获取时间，如果等到足够的token再推流，速度太慢了，想控制到300ms内开始接收token

我尝试使用`http://localhost:7870/playground/#stream`中用长文本调试，发现确实是流式，但是开始播放语音已经7-8s后了

**Comment by zhzLuke96** [comment]
首先，做不到 300ms 就开始编码，减短解码延迟会导致生成质量非常差，这是模型能力所致，详细可以跟踪这个 issues：
https://github.com/2noise/ChatTTS/issues/587

其次，流式有几秒延迟，这个是由于需要编码转换格式，目前还在看能不能优化

- 建议：
如果需要实时推送，可以使用 `raw` 格式，其直接输出模型生成的数据，音频格式为 wav （和 format=wav 不同不需要经过编码），可以在 2s左右 开始推流

也可以更快开始推理，但是质量非常差，具体效果你想测试的话，我在这个 [commit](https://github.com/lenML/Speech-AI-Forge/commit/fca1977f92c2d11b9a385809270bc8a1a642f933) 中增加了一个 接口参数 `chunk_size` ，默认为 64 ，你可以尝试改到更小的值，理论上说设置为 1 就是完全实时

- 原因：
我们只能控制 token 输出窗口，输出token之后还需要 vocos 解码，而目前的 vocos 模型对于短序列解码能力非常非常差，所以如果需要更快的响应速度需要依赖上游仓库更新或者其他新的模型
