### ISSUE TITLE
[Feature] 请问是否可以支持多音字声调修正

### ISSUE THREAD

**Issue by andywu188** [lenML/Speech-AI-Forge#182]
### 确认清单

- [X] 我已经仔细阅读[项目文档](https://github.com/lenML/ChatTTS-Forge/blob/master/README.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/lenML/ChatTTS-Forge/issues)，确认与现有issue的内容并不重复
- [X] 确认并非问题讨论而是 Feature request

### 功能描述

对某些多音字，进行修正处理：
例如：
厂家直发（第1声），植发（第4声）

### 可能的解决方案

如果能支持注音标签就好了，[fā]   [fà]

**Comment by zhzLuke96** [comment]
首先，所有基于gpt的模型都不行， chattts cosyvoice fireredtts，这是模型所致除非他们有新模型不然都没法支持多音字

f5可以支持，正在开发中

**Comment by zhzLuke96** [comment]
f5 已支持多音字注释
