### ISSUE TITLE
Support Pinyin Customization for F5-TTS

### ISSUE THREAD

**Issue by zhzLuke96** [lenML/Speech-AI-Forge#183]
计划支持 f5 模型拼音自定义
两种语法，注释和插入

注释，适合 llm 自动标注，拼音错误自动忽略
```
三人行(xing2)，必有我师焉
```

插入，适合手动标注
```
三人[xing2]，必有我师焉
```

# TODOs
- [x] refactor tokenizer (不需要只改了预处理)
- [x] text parser

**Comment by andywu188** [comment]
生成绕口令，哈哈

**Comment by zhzLuke96** [comment]
impl https://github.com/lenML/Speech-AI-Forge/commit/8749c91a09650d2de727563fb93cda08e542d22c

NOTE:
只支持 `息事宁(ning1)人` 这样的小括号语法，不准备支持大括号插入的语法，因为需要完整文本做自动拼音标注，插入一个没有字符的拼音没多大意义还更麻烦

**Comment by zhzLuke96** [comment]
关于拼音风格：
拼音声调在各个拼音之后，用数字 [1-4] 进行表示。如： `中国` -> `中(zhong1)国(guo2)`
> 同时注音系统也支持 `轻声` 即无声调韵律 `中(zhong)`

参考文档：
https://pypinyin.readthedocs.io/zh-cn/master/api.html#pypinyin.Style.TONE3
