### ISSUE TITLE
我发现会越说越快 ，不知道是不是正常的？

### ISSUE THREAD

**Issue by gg22mm** [lenML/Speech-AI-Forge#184]
### 确认清单

- [X] 我已经仔细阅读[项目文档](https://github.com/lenML/ChatTTS-Forge/blob/master/README.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/lenML/ChatTTS-Forge/issues)，确认与现有issue的内容并不重复
- [X] 确认并非问题讨论而是 Feature request

### 功能描述

测试： https://huggingface.co/spaces/lenML/ChatTTS-Forge

内容： 9月17日凌晨，刚刚在全国田径锦标赛夺冠的吴艳妮在社交平台发文，为自己第一次实现年度大满贯而感到自豪，同时祝大家中秋节快乐

**Comment by zhzLuke96** [comment]
chat tts 目前就是这样，模型问题，都不会太稳定

建议，降低 temperature， 并可以尝试更换 seed 值多生成几次
